### ISSUE TITLE
'Configuration' has no attribute 'environment'

### ISSUE THREAD

**Issue by jiujitsu** [braintree/braintree_python#47]
This code:

```python
WebhookTesting.sample_notification(
    WebhookNotification.Kind.SubscriptionWentPastDue,
    'some_id'
)
```

throws this exception:

```python
Traceback (most recent call last):
  File "/vagrant/plug/payment/tests/acceptance/test_braintree_webhooks.py", line 21, in test
    'some_id'
  File "/usr/local/lib/python2.7/dist-packages/braintree/webhook_testing.py", line 7, in sample_notification
    return Configuration.gateway().webhook_testing.sample_notification(kind, id)
  File "/usr/local/lib/python2.7/dist-packages/braintree/configuration.py", line 41, in gateway
    return braintree.braintree_gateway.BraintreeGateway(Configuration.instantiate())
  File "/usr/local/lib/python2.7/dist-packages/braintree/configuration.py", line 46, in instantiate
    environment=Configuration.environment,
AttributeError: type object 'Configuration' has no attribute 'environment'
```

I am using version 3.11.1.

**Comment by openbl** [comment]
@jiujitsu, do you have anything like the following prior to the call `WebhookTesting.sample_notification`?

```python
braintree.Configuration.configure(
    braintree.Environment.Sandbox,
    "your_merchant_id",
    "your_public_key",
    "your_private_key"
)
```

I would expect that kind of exception if you didn't set up the Configuration beforehand.

**Comment by jiujitsu** [comment]
Aha! Yes that was missing. Problem solved, sorry about that!
