### ISSUE TITLE
TypeError: data must be a byte string 

### ISSUE THREAD

**Issue by R00tCat** [braintree/braintree_python#61]
Hey there Braintree devs,

I'm getting this Python traceback whenever I try a braintree payment (in sandbox).

PIP versions, let me know if you need more info.
```
request==2.7.0
braintree==3.20.0
```

```
Traceback (most recent call last):
   [redacted]
  File "/usr/local/lib/python2.7/dist-packages/braintree/customer.py", line 102, in create
    return Configuration.gateway().customer.create(params)
  File "/usr/local/lib/python2.7/dist-packages/braintree/customer_gateway.py", line 26, in create
    return self._post("/customers", {"customer": params})
  File "/usr/local/lib/python2.7/dist-packages/braintree/customer_gateway.py", line 88, in _post
    response = self.config.http().post(self.config.base_merchant_path() + url, params)
  File "/usr/local/lib/python2.7/dist-packages/braintree/util/http.py", line 49, in post
    return self.__http_do("POST", path, params)
  File "/usr/local/lib/python2.7/dist-packages/braintree/util/http.py", line 72, in __http_do
    raise e
TypeError: data must be a byte string
```

OS: Debian 8 x64

I hope this is enough information, I'll gladly give more info about this.

**Comment by raymondberg** [comment]
Hi @rootcat. Unfortunately, this is not a good forum for troubleshooting individual issues. I would recommend opening a ticket with [Braintree support](https://support.braintreepayments.com) so you can share more details about your environment and possible information about your account setup. I'm going to close this issue out now, but if you discover through support that this is a code issue feel free to reopen.
