### ISSUE TITLE
UnexpectedError: Unexpected HTTP_RESPONSE 406 on Customer.find

### ISSUE THREAD

**Issue by vmihalachi** [braintree/braintree_python#96]
### General information

* SDK/Library version: 3.39.0
* Environment: Sandbox
* Language, language version, and OS: Python 3.6.3 on Mac OS 10.13.1

### Issue description
Hi, until yestarday it was all working. But today when I try to find the customer I get this error message. 

**Python code**
```
try:
        return braintree.Customer.find(braintree_id)
    except NotFoundError:
        return None
```

**Stacktrace**
```
Internal Server Error: /braintree/get_saved_payment_info
Traceback (most recent call last):
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/mac/PycharmProjects/clickandrap/braintree_module/views.py", line 59, in get_saved_payment_info
    credit_card = bt_helper.get_credit_card_payment_method(braintree_id)
  File "/Users/mac/PycharmProjects/clickandrap/braintree_module/bt_helper.py", line 53, in get_credit_card_payment_method
    payment_methods = get_payment_methods(braintree_id)
  File "/Users/mac/PycharmProjects/clickandrap/braintree_module/bt_helper.py", line 40, in get_payment_methods
    customer: Customer = get_braintree_customer(braintree_id)
  File "/Users/mac/PycharmProjects/clickandrap/braintree_module/bt_helper.py", line 30, in get_braintree_customer
    return braintree.Customer.find(braintree_id)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/braintree/customer.py", line 146, in find
    return Configuration.gateway().customer.find(customer_id)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/braintree/customer_gateway.py", line 36, in find
    response = self.config.http().get(self.config.base_merchant_path() + "/customers/" + customer_id)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/braintree/util/http.py", line 62, in get
    return self.__http_do("GET", path, Http.ContentType.Xml)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/braintree/util/http.py", line 91, in __http_do
    Http.raise_exception_from_status(status)
  File "/Users/mac/.local/share/virtualenvs/clickandrap-0ABdElTc/lib/python3.6/site-packages/braintree/util/http.py", line 49, in raise_exception_from_status
    raise UnexpectedError("Unexpected HTTP_RESPONSE " + str(status))
braintree.exceptions.unexpected_error.UnexpectedError: Unexpected HTTP_RESPONSE 406
```

**Comment by vmihalachi** [comment]
It was due an erroneous braintree id passed. I am closing this issue.
